apiVersion: v1
kind: Template
labels:
  template: rails-postgresql-example
metadata:
  annotations:
    description: An example Rails application with a PostgreSQL database
    iconClass: icon-ruby
    tags: instant-app,ruby,rails,postgresql
  creationTimestamp: null
  name: rails-postgresql-example
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: rails-postgresql-example
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: rails-postgresql-example
- apiVersion: v1
  kind: Route
  metadata:
    name: rails-postgresql-example
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: rails-postgresql-example
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: rails-postgresql-example
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: rails-postgresql-example
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rails-postgresql-example:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ruby:2.2
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: rails-postgresql-example
  spec:
    replicas: 1
    selector:
      name: rails-postgresql-example
    strategy:
      recreateParams:
        pre:
          execNewPod:
            command:
            - ./migrate-database.sh
            containerName: rails-postgresql-example
          failurePolicy: Abort
      type: Recreate
    template:
      metadata:
        labels:
          name: rails-postgresql-example
        name: rails-postgresql-example
      spec:
        containers:
        - env:
          - name: DATABASE_SERVICE_NAME
            value: ${DATABASE_SERVICE_NAME}
          - name: POSTGRESQL_USER
            value: ${DATABASE_USER}
          - name: POSTGRESQL_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: ${DATABASE_NAME}
          - name: SECRET_KEY_BASE
            value: ${SECRET_KEY_BASE}
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: ${POSTGRESQL_MAX_CONNECTIONS}
          - name: POSTGRESQL_SHARED_BUFFERS
            value: ${POSTGRESQL_SHARED_BUFFERS}
          - name: SECRET_KEY_BASE
            value: ${SECRET_KEY_BASE}
          - name: APPLICATION_DOMAIN
            value: ${APPLICATION_DOMAIN}
          - name: APPLICATION_USER
            value: ${APPLICATION_USER}
          - name: APPLICATION_PASSWORD
            value: ${APPLICATION_PASSWORD}
          - name: RAILS_ENV
            value: ${RAILS_ENV}
          image: rails-postgresql-example
          name: rails-postgresql-example
          ports:
          - containerPort: 8080
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - rails-postgresql-example
        from:
          kind: ImageStreamTag
          name: rails-postgresql-example:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes the database server
    name: ${DATABASE_SERVICE_NAME}
  spec:
    ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
    selector:
      name: ${DATABASE_SERVICE_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the database
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
        name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: POSTGRESQL_USER
            value: ${DATABASE_USER}
          - name: POSTGRESQL_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: POSTGRESQL_DATABASE
            value: ${DATABASE_NAME}
          - name: POSTGRESQL_MAX_CONNECTIONS
            value: ${POSTGRESQL_MAX_CONNECTIONS}
          - name: POSTGRESQL_SHARED_BUFFERS
            value: ${POSTGRESQL_SHARED_BUFFERS}
          image: postgresql
          name: postgresql
          ports:
          - containerPort: 5432
    triggers:
    - imageChangeParams:
        automatic: false
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:9.4
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The URL of the repository with your application source code
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/openshift/rails-ex.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository
  name: CONTEXT_DIR
- description: The exposed hostname that will route to the Rails service, if left
    blank a value will be defaulted.
  name: APPLICATION_DOMAIN
- description: A secret string used to configure the GitHub webhook
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- description: Your secret key for verifying the integrity of signed cookies
  from: '[a-z0-9]{127}'
  generate: expression
  name: SECRET_KEY_BASE
- description: The application user that is used within the sample application to
    authorize access on pages
  name: APPLICATION_USER
  value: openshift
- description: The application password that is used within the sample application
    to authorize access on pages
  name: APPLICATION_PASSWORD
  value: secret
- description: Environment under which the sample application will run. Could be set
    to production, development or test
  name: RAILS_ENV
  value: production
- description: Database service name
  name: DATABASE_SERVICE_NAME
  value: postgresql
- description: database username
  from: user[A-Z0-9]{3}
  generate: expression
  name: DATABASE_USER
- description: database password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: DATABASE_PASSWORD
- description: database name
  name: DATABASE_NAME
  value: root
- description: database max connections
  name: POSTGRESQL_MAX_CONNECTIONS
  value: "100"
- description: database shared buffers
  name: POSTGRESQL_SHARED_BUFFERS
  value: 12MB
